version: 2
working_directory: &working_directory ~/workspace
base: &base
  working_directory: *working_directory
  docker:
    - image: circleci/node:10
  steps:
    - checkout
    - restore_cache:
        key: ashe-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Install dependencies
        command: npm i
    - run:
        name: Build
        command: npm run ci
    - save_cache:
        key: ashe-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
          - 'node_modules'

jobs:
  build_node_10:
    <<: *base
    docker:
      - image: circleci/node:10

  build_node_12:
    <<: *base
    docker:
      - image: circleci/node:12

  publish:
    docker:
      - image: circleci/node:12
    working_directory: *working_directory
    steps:
      - checkout
      - restore_cache:
          key: ashe-tag-master-{{ checksum "package.json" }}
      - run:
          name: Build
          command: |
            npm i
            npm run ci
      - run:
          name: Generate CHANGELOG.md
          command: |
            npm version ${CIRCLE_TAG/v/}
            npm run changelog
      - run:
          name: Publish
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            npm publish --access public
            echo "Publish success!!"
      - run:
          name: Push to Github
          command: |
            sh ./git.sh
            git push -q "https://$GITHUB_TOKEN@github.com/doxiaodong/ashe.git" $(git rev-parse --abbrev-ref HEAD):master
            echo "Push success!!"
      - save_cache:
          key: ashe-tag-master-{{ checksum "package.json" }}
          paths:
            - 'node_modules'

workflows:
  version: 2
  build:
    jobs:
      - build_node_10
      - build_node_12
  tagged-build:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
